spring.application.name=Smart Email Assistant
<<<<<<< HEAD

#//environment variables
gemini.api.url = ${GEMINI_API_URL}
=======
gemini.api.url = ${GEMINI_API_URl}
>>>>>>> 6e8489e (Your feature edits)
gemini.api.key = ${GEMINI_API_KEY}